## default connection pool
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/community_help"

otp-verification-template: "Your CoGiv verification code is %s"

sns:
  accessKey: 'abcde'
  secretKey: 'abcde'

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8085

jwt:
  issuer: Scaler
  secret: 2FP8Wlc4ADlMdxti2jLRsdbasjkdbajskasl6781357263dsnmbdjsadkjuteqwiewF9IjBMQyYKsIVsBPIDgX_iXyPeHQzFmPmPpGts9OpDuaFxGCPpb9mD9xWpSEMcxInaB_DDZtYE7SncLNFUCrQR_XoGY_vp4II3ssuxUI7G0IfPebmllUSh8JcGBkPVh9Ksqa-vReoGmy6TnXcGT_K8nZfDdVoFs1am-EUnVhUYjC94BAOLKasDWxjlHdltALiIWdpyncCX5NCh8vjVXRPQeiADJiW13gUKs-d2o6c-V3y1ABAVnw52r5O50oWmpoJS1FqqvH7dqjs8OvejlYCZKKEkKOVVvUgx604Jm_6UKr4VxUJydLrXqKW0y1nFXqA